#!/bin/bash

me=$(users)
 
#if [ "$EUID" -ne 0 ]; then
if [[ $EUID > 0 ]]; then
    echo "Veuillez executer le script en tant que root"
    exit 0
fi
 
echo "Bonjour, quel utilisateur souhaitez-vous supprimer ? :"
 
read varname
 
if [ -z "$varname" ]; then
    echo  "Argument vide\nFin du programme."
    exit 0
fi
 
if [ -z $(pgrep -u "$varname" 2>/dev/null) 2>/dev/null ]; then
    echo ""$varname" n'est pas connecte"
    exit 0
else
    echo ""$varname" est connecte"
    if [ "$varname" = $USER ]; then
        echo "Impossible de vous auto-supprimer"
        exit 0
    elif [ "$varname" = "$me" ];then
        echo "Impossible de vous auto-supprimer"
        exit 0
    else
        echo "Voulez vous vraiment supprimer "$varname" ? "
        echo "OUI : NON ? "
    read answer
    if [ "$answer" = "NON" ]; then
        echo ""$varname" ne va pas etre supprime\nFin du programme"
        exit 0
    elif [ $answer = "OUI" ]; then
        echo "Suppression de "$varname" en cours ...."
        passwd -l $varname
        pkill -KILL -u $varname
        userdel -r -f $varname
        echo "Suppression termine"
        exit 0
    else
        echo "Reponse attendu : "OUI" ou "NON""
        echo "Fin du programme"
        exit 0
    fi
fi
fi
exit
