#!/bin/bash

red=$'\e[1;31m'
grn=$'\e[1;32m'
yel=$'\e[1;33m'
blu=$'\e[1;34m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
end=$'\e[0m'


clear
printf "Hello "$USER", you want to encrypte or decrypte a file ?\n"

printf "${blu}Enter [1] for encrypte or [2] to decrypte and type ENTER${end}\n"

read ACTION

clear 

printf "Enter the name of the output file :\n"

read  OUTPUT

printf "Which file do you want to work on ?\n"

read FILE

if [ $ACTION = 1 ]; then
	printf "${yel}Checking if $FILE exist ...${end}\n"
	if [ -f "$FILE" ]; then
		printf "${grn}$FILE exist${end}\n"
	else
		printf "${red}$FILE doesn't exist, please enter a valid file name${end}\n"
		printf "Program stopped\n"
		exit 0
	fi
	printf "${red}I'll ask you an encryption password, DON'T FORGET IT or you will loose $FILE ${end}\n"
	openssl enc -AES-256-CBC -in $FILE -out $OUTPUT
	clear
	printf "${grn}$FILE is encrypted. $OUTPUT created.${end}\n"

elif [ $ACTION = 2 ]; then
	printf "${yel}Checking if $FILE exist ...${end}\n"
	if [[ -f "$FILE" ]]; then
		printf "${grn}$FILE exist${end}\n"
	else
		printf "${red}$FILE doesn t exist, please enter a valid file name ${end}\n"
		printf "Program stopped\n"
		exit 0
	fi
	clear
	openssl enc -AES-256-CBC -d -in $FILE -out $OUTPUT
	printf "${grn}$FILE is decrypted. $OUTPUT created.${end}\n"
fi
exit 0
