#!/bin/bash

echo "Hello "$USER", you want to encrypte or decrypte a file ?\n"


echo "Enter 1 for encrypte or 2 to decrypte and type ENTER\n"

read ACTION

echo "Enter the name of the output file :\n"

read OUTPUT

echo "Which file do you want to work on ?\n"

read FILE

if [ $ACTION = 1 ]; then
	printf "Checking if $FILE exist ...\n"
	if [ -f "$FILE" ]; then
		printf "$FILE exist\n"
	else
		printf "$FILE doesn't exist, please enter a valid file name\n"
		printf "Program stopped\n"
		exit 0
	fi
	printf "I'll ask you an encryption password, DON'T FORGET IT or you will loose $FILE\n"
	openssl enc -AES-256-CBC -in $FILE -out $OUTPUT
	printf "$FILE is encrypted. $OUTPUT created.\n"
	echo "For better safety and privacy I can remove the non encrypted file $FILE, do you want me to remove it ? [Y/n]\n"
	read RM
	if [ "$RM" != "${RM#[Yy]}" ]; then
		printf "Removing $FILE\n"
		rm $FILE
	else
		printf "$FILE will not be deleted\n"
	fi
	exit 1


elif [ $ACTION = 2 ]; then
	printf "Checking if $FILE exist ...\n"
	if [[ -f "$FILE" ]]; then
		printf "$FILE exist\n"
	else
		print "$FILE doesn t exist, please enter a valid file name\n"		
		printf "Program stopped\n"
		exit 0
	fi
	openssl enc -AES-256-CBC -d -in $FILE -out $OUTPUT
	printf "$FILE is decrypted. $OUTPUT created.\n"
	exit 1
fi
exit 0
